config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :contacts, except: :show do
    post :generate, on: :collection
  end

  root 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.order(:first_name, :last_name)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to contacts_path, notice: 'Your contact has been created.'
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to contacts_path, notice: 'Your contact has been updated.'
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])

    if @contact.destroy
      redirect_to contacts_path, notice: 'Your contact has been deleted.'
    else
      redirect_to contacts_path, alert: 'Your contact couldn\'t be deleted.'
    end
  end

  def generate
    if GenerateSampleContactsJob.perform_later(samples: 5)
      redirect_to contacts_path, notice: 'Your request to create sample contacts has been dispatched.'
    else
      redirect_to contacts_path, alert: 'Your request to create sample contacts has failed to dispatch.'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(
      :first_name, :last_name, :street_address, :zip_code, :city, :country_code, :email, :phone_number, :twitter, :avatar_url
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= form_for contact do |f| %>
  <div class="row">
    <div class="form-group col-sm-6">
      <%= f.label :first_name, class: 'control-label' %>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-6">
      <%= f.label :last_name, class: 'control-label' %>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :street_address, class: 'control-label' %>
    <%= f.text_field :street_address, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="form-group col-sm-2">
      <%= f.label :country_code, class: 'control-label' %>
      <%= f.text_field :country_code, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-2">
      <%= f.label :zip_code, class: 'control-label' %>
      <%= f.text_field :zip_code, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-8">
      <%= f.label :city, class: 'control-label' %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :phone_number, class: 'control-label' %>
      <%= f.text_field :phone_number, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label :email, class: 'control-label' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group col-sm-4">
      <%= f.label :twitter, class: 'control-label' %>
      <%= f.text_field :twitter, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :avatar_url, class: 'control-label' %>
    <%= f.url_field :avatar_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "#{contact.new_record? ? 'Create' : 'Save'} Contact", class: 'btn btn-success' %>
    <%= link_to 'Back to Contacts', contacts_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h2>Edit Contact</h2>

<%= render partial: 'form', locals: { contact: @contact } %>

app/views/contacts/index.html.erb
<div class="pull-right"><%= link_to 'New Contact', new_contact_path, class: 'btn btn-success' %></div>
<div><%= link_to 'Generate Sample Contacts', generate_contacts_path, method: :post, class: 'btn btn-info' %></div>

<div class="contacts row">
  <% if @contacts.size > 0 %>
    <% @contacts.each do |contact| %>
      <div class="col-sm-4">
        <div class="contact">
          <div class="pull-left">
            <%= image_tag contact.avatar_url, class: 'avatar' %>
            <%= link_to 'Edit', edit_contact_path(contact), class: 'btn btn-xs btn-warning edit-link btn-block' %>
            <%= link_to 'Delete', contact_path(contact), method: :delete, class: 'btn btn-xs btn-danger delete-link btn-block' %>
          </div>
          <p><%= link_to "#{contact.first_name} #{contact.last_name}", contact, class: 'name' %></p>
          <p><%= link_to "@#{contact.twitter}", "https://twitter.com/#{contact.twitter}" %></p>
          <p>
            <%= contact.street_address %><br>
            <%= contact.country_code %>-<%= contact.zip_code %>, <%= contact.city %>
          </p>

          <p>
            Phone: <%= contact.phone_number %><br>
            Email: <%= link_to contact.email, "mailto:#{contact.email}" %>
          </p>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-sm-12 text-center">
      There are no contacts yet. <%= link_to 'Create one', new_contact_path %>.
  <% end %>
</div>

app/views/contacts/new.html.erb
<h2>Create New Contact</h2>

<%= render partial: 'form', locals: { contact: @contact } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <h1>Contacts</h1>
  <hr>

  <% flash.each do |type, message| %>
    <div class="alert <%= type == 'notice' ? 'alert-success' : 'alert-danger' %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

  <hr>
  <p class="text-center">Robots lovingly delivered by <a href="http://robohash.org" target="_blank">Robohash.org</a>.</p>
</div>

</body>
</html>